services:
  - type: web
    name: treno-web
    env: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
    plan: free
    region: singapore
    branch: main
